swagger: '2.0'
info:
  description: >-
    This is a sample server.  You can find out more about    
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).      For this sample, you can use the api
    key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /et
tags:
  - name: jobject 
    description: JSON Objects
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /jobject:
    post:
      tags:
        - jobject
      summary: Pass in object
      description: Non Description
      operationId: passObject 
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: JSON Object
          required: true
          schema:
            $ref: '#/definitions/JOBject'
      responses:
        default:
          description: successful operation
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  JOBject:
    type: object
    properties:
      id:
        type: integer
        format: int64
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
